{% set name = "matcalc" %}
{% set version = "0.4.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/matcalc-{{ version }}.tar.gz
  sha256: ea3e9eaf441677175cd9d1bfcf9a5e532ca4386235638956b046c2ca48dbbf77

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - numpy
    - setuptools >=58.0.3
    - pip
  run:
    - phono3py >=3.15.0
    - fsspec >=2025.3.0
    - numpy <2.0.0
    - python >={{ python_min }}
    - ase >=3.23.0
    - joblib >=1.4.2
    - phonopy >=2.38.0
    - pymatgen >=2025.4.20
    - scikit-learn >=1.6.1

test:
  imports:
    - matcalc
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://materialsvirtuallab.github.io/matcalc
  summary: Calculators for materials properties from the potential energy surface.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
