{% set name = "matcalc" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/matcalc-{{ version }}.tar.gz
  sha256: 4a78774ecb868def5ff9bc8f63895bd7a9acd86f0ac3c8706d7a547121398e9b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - numpy
    - setuptools >=58.0.3
    - pip
  run:
    - numpy <2.0.0
    - python >={{ python_min }}
    - ase >=3.23.0
    - joblib
    - phonopy
    - pymatgen

test:
  imports:
    - matcalc
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://materialsvirtuallab.github.io/matcalc
  summary: Calculators for materials properties from the potential energy surface.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
