{% set name = "matcalc" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/matcalc-{{ version }}.tar.gz
  sha256: 581961a237d23fd7c8cef6478460e405c2cef45a3c34a48f22c8eae1c1c4ec90

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - numpy
    - setuptools >=58.0.3
    - pip
  run:
    - python >={{ python_min }}
    - ase
    - joblib
    - phonopy
    - pymatgen

test:
  imports:
    - matcalc
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://materialsvirtuallab.github.io/matcalc
  summary: Calculators for materials properties from the potential energy surface.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
